# Generated by Django 3.2.4 on 2021-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='image', max_length=200, verbose_name='Image Name'),
        ),
    ]
